### ISSUE TITLE
ALE allows one to set inexistent flags

### ISSUE THREAD

**Issue by mcmachado** [mgbellemare/Arcade-Learning-Environment#76] opened 2015-07-10 19:57 UTC
If we try to set an inexistent flag, the ALE is not going to forbid us. E.g.: `ale.setFloat("stochasticity", 0.00)` works just fine (no exception is thrown, no error message is given, it just ignores the command).

I don't think we should allow it. I think we should give **at least** a warning. While inexistent flags may be unlikely, typos are not.

**Comment by mgbellemare** [comment] 2015-07-12 17:14
That sounds like a good idea. One easy way about this is to prevent inserting new options in Settings.cxx in setInternal/setExternal (only allow replaces), and add a method 'defineXXXX' that would explicitly add a new option. Then we could add all the options, e.g. in Defaults.cpp (but perhaps somewhere better).

**Comment by spragunr** [comment] 2015-07-14 16:15
A related issue: no exception occurs when getting the value of non-existent flags.  Using the python interface:

    In [27]: ale.getBool('doesnt_exist')
    Out[27]: False

    In [28]: ale.getFloat('doesnt_exist')
    Out[28]: -1.0

I assume the behavior is the same for C++.

**Comment by mcmachado** [comment] 2015-07-22 00:22
@spragunr , even though I did not test, I believe this is the behavior in C++ as well.

@mgbellemare , what do you think if implement a method in Settings.cxx called checkKey(const string& key) which is called at the beginning of every get/set method?

This method would have an array with all the available keys and we would just iterate over this array to make sure the key being set (or being requested) exists. If it does not, we exit, ending the program (or throw an exception, something that we do not generally do).

**Comment by Jragonmiris** [comment] 2015-08-08 11:31
I'd say setting something that does not exist is an exceptional case. It is not something that should reasonably happen in a well-defined program, a crash is warranted. 

Though I'd argue some `map` type or another (std::map?) is probably more conceptually appropriate than an array, but the key set is so small it doesn't practically matter.

**Comment by mgbellemare** [comment] 2015-08-09 12:59
@Jragonmiris Yes, an unordered map would work better here; I'm not sure why the Stella developers used an array. For now though their data structure works fine, so it might not be worth fixing immediately. I would argue against the accessor method approach here, as you say because of bloat but also because it feels bug-prone (lots of effectively duplicated code).

@mcmachado I believe we discussed a solution in person. Can I let you take the lead on this issue?

**Comment by mcmachado** [comment] 2015-08-09 16:33
@mgbellemare I will do it as soon as possible. Hopefully this week, maybe next week.

**Comment by mgbellemare** [comment] 2015-10-04 20:50
Fixed with PR #107 .

**Comment by mgbellemare** [comment] 2015-10-04 21:08
@mcmachado : it looks like #107 isn't quite complete. See line 90 of ale_interface.cpp: getString("random_seed") returns 123 instead of crashing. Is this expected behaviour?

**Comment by mcmachado** [comment] 2015-10-04 21:15
@mgbellemare, are you running the example? Because in the main function of our sharedLibraryExample we set the random_seed to be 123. If this is what is happening, it is expected.

**Comment by mgbellemare** [comment] 2015-10-04 21:16
My point was more that random_seed is an int argument, but we're reading it with getString(). This is valid under the old version because internally all settings are stored as strings. We can keep this as such, but should do so carefully.

**Comment by mcmachado** [comment] 2015-10-04 21:32
You are right. I didn't change the get functions. I was concerned in changing how users set the variables. Internally, in Settings.cxx, we set every variable in setExternal and both the key and the values are string for all variables. If we want to change this, it is a much bigger change, with more serious consequences. This is why I didn't change it, we would have to refactor the whole class.

**Comment by mgbellemare** [comment] 2015-10-04 21:41
No problem. It's a fairly minor issue compared to the setting of invalid flags.

**Comment by mcmachado** [comment] 2015-10-08 22:06
Should we close this issue?

**Comment by mgbellemare** [comment] 2015-10-08 23:02
Yes. FYI, you can tell GitHub to automatically close your issues by including certain tags in your commit messages. See #63 .

**Closed by mgbellemare** 2015-10-08 23:02 UTC

**Comment by mcmachado** [comment] 2015-10-08 23:30
I wanted to make sure everyone agreed on that...
I didn't know that, I'll look into it.

**Comment by Jragonmiris** [comment] 2015-10-09 00:00
Yeah, you can close an issue from a commit by putting "Fixes
#commit-reference" in it. When you merge a PR, you usually do it from the
merge commit message.
