### ISSUE TITLE
[BUG] Installation of python 3.10 manylinux wheels on PyPI fail on some machines

### ISSUE THREAD

**Issue by vmoens** [mgbellemare/Arcade-Learning-Environment#469] opened 2022-09-09 05:50 UTC
# Description of the problem

Installing the manylinux binaries 
[ale_py-0.8.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl](https://files.pythonhosted.org/packages/60/1b/3adde7f44f79fcc50d0a00a0643255e48024c4c3977359747d149dc43500/ale_py-0.8.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl) fails on some machines (e.g. see [the CI](https://app.circleci.com/pipelines/github/facebookresearch/rl/2779/workflows/52cb8e39-7b76-49fc-acc9-fad1d0c37794) for [this commit](https://github.com/facebookresearch/rl/commit/9421aca96631427a8ea84e7fc828bbfc40ca09dd) on python 3.10: all jobs are failing because when installing ale-py, gym 0.26 is reverted to 0.25.2 as the 0.8.0 version of ale-py cannot be installed)

# Proposed fix

Renaming the wheels to `ale_py-0.8.0-cp310-cp310-manylinux_2_27_x86_64.manylinux2014_x86_64.whl` seems to fix the issue.

**Comment by JesseFarebro** [comment] 2022-09-09 11:21
Hi @vmoens, upgrading pip should fix this. A simple `pip install -U pip` will do the trick. Let me know if this still doesn't fix the issue for you.

**Comment by vmoens** [comment] 2022-09-09 14:00
Thanks for this
I tried upgrading pip and it still breaks

For ref:
https://github.com/facebookresearch/rl/pull/403/commits/e9a6e3f449def3026f44f029301198028193d833

Tests:
https://app.circleci.com/pipelines/github/facebookresearch/rl/2804/workflows/8ff53b69-ee8a-4e2b-b934-dab890dbf16e/jobs/52049

**Comment by JesseFarebro** [comment] 2023-02-17 06:39
Duplicate of #478. This is fixed as of v0.8.1 🙌

**Closed by JesseFarebro** 2023-02-17 06:39 UTC
