### ISSUE TITLE
SDL display hangs in manual mode at end of episode

### ISSUE THREAD

**Issue by mgbellemare** [mgbellemare/Arcade-Learning-Environment#138] opened 2016-01-11 22:36 UTC
Playing a game with the SDL display and keyboard controls, the game will hang when the episode
terminates, as noted by @nowozin .

**Comment by ionelhosu** [comment] 2016-05-15 12:20
The hang is caused by the fact that in manual mode, after an episode terminates, there is no call to _ale.reset_game()_. For example, if you run _python_example.py_ (which should play 10 episodes) and control the agent from the keyboard, the display will hang after the first game, but only because _ale.reset_game()_ is not called.

In the case of _python_example.py_, the hang can be fixed by briefly turning off and on again manual control (pressing M twice). By doing this, the main loop will execute again and _ale.reset_game()_ will be called. I guess there is the elegant solution of adding the capability to press a key to reset the game, or to automatically reset the game when the episode ends and we are in manual control mode.

**Comment by JesseFarebro** [comment] 2021-08-21 23:30
Manual mode is no longer supported in the ALE although you can still use manual control via Gym or by writing a basic script to take keyboard input.

**Closed by JesseFarebro** 2021-08-21 23:30 UTC
Labels: bug, sdl
